export const SET_USER_AUTHENTIFICATION = 'SET_USER_AUTHENTIFICATION';
export const SHOW_TOAST = 'SHOW_TOAST';
export const CLEAR_TOAST = 'CLEAR_TOAST';
export const SET_APARTMENTS = 'SET_APARTMENTS';
